/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWeightRouteImport } from './routes/_app/weight'
import { Route as AppWalkRouteImport } from './routes/_app/walk'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeightRoute = AppWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AppRoute,
} as any)
const AppWalkRoute = AppWalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/insights': typeof AppInsightsRoute
  '/plan': typeof AppPlanRoute
  '/settings': typeof AppSettingsRoute
  '/walk': typeof AppWalkRoute
  '/weight': typeof AppWeightRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/insights': typeof AppInsightsRoute
  '/plan': typeof AppPlanRoute
  '/settings': typeof AppSettingsRoute
  '/walk': typeof AppWalkRoute
  '/weight': typeof AppWeightRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/walk': typeof AppWalkRoute
  '/_app/weight': typeof AppWeightRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/insights'
    | '/plan'
    | '/settings'
    | '/walk'
    | '/weight'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/insights' | '/plan' | '/settings' | '/walk' | '/weight' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/insights'
    | '/_app/plan'
    | '/_app/settings'
    | '/_app/walk'
    | '/_app/weight'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weight': {
      id: '/_app/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AppWeightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/walk': {
      id: '/_app/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof AppWalkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInsightsRoute: typeof AppInsightsRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWalkRoute: typeof AppWalkRoute
  AppWeightRoute: typeof AppWeightRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInsightsRoute: AppInsightsRoute,
  AppPlanRoute: AppPlanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWalkRoute: AppWalkRoute,
  AppWeightRoute: AppWeightRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
